language: python
sudo: false
notifications:
  email: false
python:
  - 2.7
  - 2.7_with_system_site_packages
  - 3.4
env:
  - QT_API=pyside
  - QT_API=pyqt
addons:
  apt:
    packages:
    - python-qt4-dev
    - python-qt4-gl
    - ccache
    - cmake
matrix:
  exclude:
    - python: 2.7_with_system_site_packages
      env: QT_API=pyside
    - python: 2.7
      env: QT_API=pyqt
    - python: 3.4
      env: QT_API=pyqt
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - pip install --upgrade pip
  - export PATH=/usr/lib/ccache:${PATH}
  - ./build_pyside_wheel.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install -r dev_requirements.txt
  - flake8
  - python setup.py develop -N
before_script:
  - mkdir testrun
  - cd testrun
  - cp ../.coveragerc .
script:
  - coverage run -m nose.core -v qt_binder
after_success:
  - pip install codecov
  - codecov
