language: python
sudo: false
notifications:
  email: false
python:
  - 2.7
  - 3.4
branches:
  # We have both "Build pushes" and "Build PRs" turned on. Without the
  # following setting, Travis CI will do 2 builds for every update to a PR, one
  # which is tested as merged into master (what we want) and one just as the
  # raw PR branch (meh). We'd also like to run an additional test for any
  # pushes to master (which should only be PR merges). The following setting
  # whitelists master as a branch for the "push" builds. PR builds will happen
  # regardless. If you want your WIP branches tested, open up a WIP PR.
  only:
    - master
addons:
  apt:
    packages:
    - python-qt4-dev
    - python-qt4-gl
    - ccache
    - cmake
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - pip install --upgrade pip
  - export PATH=/usr/lib/ccache:${PATH}
  - ./build_pyside_wheel.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install -r dev_requirements.txt
  - flake8
  - python setup.py develop -N
before_script:
  - mkdir testrun
  - cd testrun
  - cp ../.coveragerc .
script:
  - coverage run -m nose.core -v qt_binder
after_success:
  - pip install codecov
  - codecov
